FROM node:14.4.0-alpine3.11 as builder
WORKDIR /app
COPY . .
RUN npm install && npm run build

FROM nginx:alpine
COPY --from=builder /app/public/ /usr/share/nginx/html/
# COPY --from=builder /app/public/global.css /usr/share/nginx/html/
# COPY --from=builder /app/public/index.html /usr/share/nginx/html/
# COPY --from=builder /app/public/build /usr/share/nginx/html/build/
